# Generated by Django 3.2.8 on 2021-12-03 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20211128_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
