# Generated by Django 3.2 on 2021-04-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='start_bid',
            field=models.IntegerField(),
        ),
    ]
