# Generated by Django 3.2 on 2021-04-14 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210414_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='created_for',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_to_buy', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_bid',
            field=models.IntegerField(default=1),
        ),
    ]
