# Generated by Django 3.2 on 2021-05-02 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='item',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='listing',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='watched_item', to='auctions.listing'),
        ),
    ]
