# Generated by Django 3.2 on 2021-05-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210503_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img_url',
            field=models.URLField(blank=True, default='https://thumbs.dreamstime.com/b/new-product-grunge-vintage-stamp-isolated-white-background-new-product-sign-new-product-stamp-153380133.jpg'),
        ),
    ]
